### ISSUE TITLE
Redundant connections opened and held with 2.7.3

### ISSUE THREAD

**Issue by shaib** [psycopg/psycopg2#612] opened 2017-11-08 12:04 UTC
Hello,

At Matific, We have long been using psycopg2 with Django on a system running on AWS and RDS, and have been very pleased. Recently, we upgraded from 2.7.1 to 2.7.3.1, and following the upgrade found that a lot more connections are being opened and kept open than before -- in fact, we encountered failures because we ran out of connections to use.

Downgrading back to 2.7.1 made the problem go away.

We use Django 1.8 and specify the "CONN_MAX_AGE" setting, which means that once a thread opens a connection, it is supposed to be kept open; but AFAIK connections are not supposed to open until triggered by the handling of requests. What we saw with 2.7.3 was, essentially, that every thread held a connection (we used up to 6 worker processes, up to 20 threads each). Oh, and we use two connections (to separate database servers) in each thread.

We suspected the upgrade because we saw the mention of "Fixed inconsistent state in externally closed connections (ticket #263, ticket #311, ticket #443)" in the 2.7.2 release notes (and, of course, because we encountered the problem right after it).

Python 2.7, Amazon's standard Linux image, Amazon RDS's PG 9.4 on the DB servers. I'm guessing this is not enough info for full investigation, we'll try our best to provide any more information necessary.

**Comment by dvarrazzo** [comment] 2017-11-08 14:59
Hello,

as pointed out in these bug, the problem fixed is about considering the connection "closed" in psycopg state when it gets closed for external behaviour. So while I don't rule out your problem is caused by these fixes I don't see a direct connection either.

You should investigate better what your django app does. I understand *connections are not supposed to open until triggered by the handling of requests*, but whether this works as expected or not is a django behaviour, not psycopg.

I will close this bug as there is no evidence a psycopg is doing anything wrong. I will reopen it in case you prove me wrong.

**Closed by dvarrazzo** 2017-11-08 14:59 UTC

**Comment by shaib** [comment] 2017-11-08 21:39
There is one piece of evidence, as far as I'm concerned, that psycopg is doing something wrong, and that is that we have a problem with 2.7.3 and no problem with 2.7.1. That said, I understand (said so myself) that my report above does not provide enough info, I was just hoping for some guidance about things to look into. I will try to investigate further.

**Comment by dvarrazzo** [comment] 2017-11-08 22:50
I have read that, but that upgrade in itself doesn't do much. Sure it doesn't decide to open connections itself. So it can be that some subtle effect of that fix has compounded with another problem in Django (not very likely) or in your app (more likely).
