### ISSUE TITLE
upgrade from 2.7.7 to 2.8.1 leaves connections open in idle state

### ISSUE THREAD

**Issue by erichanson** [psycopg/psycopg2#889] opened 2019-04-07 02:19 UTC
Change of behavior after upgrade to 2.8.1 via pip install on Ubuntu 18.04 and also Debian 9.

uWSGI/werkzeug/psycopg2 app (https://bit.ly/2UBxVmR) which had been working fine for years broke on upgrade from 2.7.7 to 2.8.1.  After the upgrade, it just leaves all connections open to the database in idle state, until it hits max_connections, then crashes.

**Comment by dvarrazzo** [comment] 2019-04-07 09:34
Hi,

no change in 2.8 should have resulted in that. Can you provide a self-contained test case showing the change in behaviour?

**Comment by dvarrazzo** [comment] 2019-04-07 10:04
Again, I'm not aware of what change in 2.8 could have resulted in this change of behaviour and my intention is to fix it if possible, but this code could be definitely more robust.

Taking a cursory look at your code, I see you rely heavily on the GC to close connections. Your `cursor_for_request()` could definitely close the connection on exit. I'm somewhat sure that something like the following would fix your code:

```diff
diff --git a/src/py-package/uwsgi-endpoint/endpoint/db.py b/src/py-package/uwsgi-endpoint/endpoint/db.py
index d85d549..946629d 100644
--- a/src/py-package/uwsgi-endpoint/endpoint/db.py
+++ b/src/py-package/uwsgi-endpoint/endpoint/db.py
@@ -18,9 +18,13 @@ def connect(request):
 
 @contextmanager
 def cursor_for_request(request):
-    with connect(request) as db_conn:
-        cursor = db_conn.cursor()
-        yield cursor
+    try:
+        with connect(request) as db_conn:
+            cursor = db_conn.cursor()
+            yield cursor
+
+    finally:
+        db_conn.close()
 
 
 @contextmanager
```

Maybe that function was written with the wrong assumption that `with connection` closes the connection on exit, but no: it only [closes the transaction](http://psycopg.org/psycopg/docs/usage.html#with-statement).

A potential change which could have accidentally make your app work previously could be fixing #829. Does your app rely on forking/multiprocessing?

Not related to the bug, but `map_errors_to_http()` could definitely catch only [`DatabaseError`](http://psycopg.org/psycopg/docs/module.html#psycopg2.DatabaseError) instead of 5 of its subclasses, use [`Error.pgcode`](http://psycopg.org/psycopg/docs/module.html#psycopg2.Error.pgcode), [`Error.diag`](http://psycopg.org/psycopg/docs/module.html#psycopg2.Error.diag) to dispatch into http errors, or, using 2.8, the [`errors` module](http://psycopg.org/psycopg/docs/errors.html#module-psycopg2.errors).

Furthermore, it is unwise having your app depending on whatever major release of a package without testing.  If you tested your app with psycopg ver. 2.7.x you should probably express your dependency as 
 `psycopg2>=2.7,<2.8` (this is not a psycopg thing, just a general good practice).

**Comment by dvarrazzo** [comment] 2019-04-07 10:29
Hint: you could use `pg_stat_activity` to figure out the last query run by the orphaned connection to figure out which one is the python bit that leaves them open.

**Comment by erichanson** [comment] 2019-04-07 12:50
Code could definitely be more robust.  :)  I just thought it was worth mentioning because switching back and forth between 2.7 and 2.8 makes the behavior appear and disappear.  I did make a lot of debugging changes adding`db_conn.close()` statements but they didn't fix it so far.   `pg_stat_activity` says last query was `COMMIT`.  This project isn't in production, far from it.  Right now I'm working around the issue by just explicitly installing `psycopg==2.7.7` which resolved the issue, though I would like to stay on the current-train.

**Comment by erichanson** [comment] 2019-04-07 13:09
I applied the patch you provided suggested, did not fix.  Here is the contents of `pg_stat_activity`:

https://gist.github.com/erichanson/2d888a00bce83cbad220debd007081db

**Comment by dvarrazzo** [comment] 2019-04-07 13:51
Are there other code paths using connections apart the ones going through `cursor_for_request()`?

**Comment by dvarrazzo** [comment] 2019-04-07 13:55
Also, is this Python 2 or 3? If it's Py3 do you want to try reverting 17b0c613380 to understand if it was multiprocessing eagerly closing connections for other processes as per #829?

**Comment by erichanson** [comment] 2019-04-07 14:04
This is on Python 2.  Nothing touches the db without going through `cursor_for_request`.

**Comment by dvarrazzo** [comment] 2019-04-07 14:18
In this case no, probably #829 wasn't working in your favour. The COMMITs come from the exit of the connection context, so that's triggered ok but then the connection is not closed (weird your added `close()` on context exit didn't affect it, isn't it?

If you want to see the last statements then I guess you should enable statements logging in the server, or use some form of logging cursor on the client (a not very good one is included in the package, but it's easy to make one of yours).

**Comment by erichanson** [comment] 2019-04-07 14:46
Heyy I was your your patch did resolve the issue.  I was doing `pip install --force-reinstall .` instead of `--upgrade`.  Back on current!  Thank you.

There is still a change of behavior here is seems?  Did `cursor.close()` used to close the connection without needing to call `conn.close()`?

Thank you for your help.

**Comment by erichanson** [comment] 2019-04-07 14:50
Also I will refactor that error handling.  The `errors` module looks nice.

**Comment by dvarrazzo** [comment] 2019-04-07 14:57
I don't know. Quite a few things changed between 2.7 and 2.8, but I don't have a specific one which would cause this behaviour. No, closing a cursor doesn't close a connection.

Could it be that because uWSGI the connection is opened in one process and closed in another? Because if so yes, psycopg will not close it anymore (sharing a connection across processes shouldn't be done, but it's not explicitly checked, because I actually thought it wouldn't have worked; maybe such check could be added). You could try printing `os.getpid()` on connection open and close and verify if they differ.

it would be great if you get to the bottom of why the behaviour changed, thank you.

**Comment by erichanson** [comment] 2019-04-07 15:23
Right, now I am wondering why the old code ever worked.  It didn't call `conn.close()` ever, but connections where closing somehow.

**Comment by dvarrazzo** [comment] 2019-04-07 15:32
Connections were closed on GC, but it's not the most reliable of the ways (if there is something that keeps the python connection object alive, they won't be closed, that's why explicit is better).

That's still true (and our test suite hasn't detected regressions). However if there is a fork-exec thing and connection is opened in one process and closed in another, the gc will not close the connection automatically to avoid the problem described in #829.

There could be some more subtle change in objects references so that now the connection is kept alive, but honestly I don't think that's the case. If it was, happy to fix.

**Comment by dvarrazzo** [comment] 2019-04-08 20:25
Hi,

can i close this bug or there is anything to fix on our side?

**Comment by erichanson** [comment] 2019-04-09 00:41
Well, I got it working so I'm fine.  There was a change of behavior, I believe it involves garbage collection as you suggested.  But since we were not explicitly closing connections, I suppose it's up to you whether we were just misusing the library and it's ok for it to break, or if the GC should be freeing those connections.  I am not very adept at GC debugging but was learning about `weakref` a bit, if I track down the behavior change, I will post it here.

**Comment by dvarrazzo** [comment] 2019-04-09 00:51
The GC closes the connection alright normally:

```
$ PSYCOPG_DEBUG=1 ipython
In [1]: import psycopg2
[16529] psycopgmodule: initializing psycopg 2.8.2.dev0 (dt dec mx pq3 ext lo64)
[...]

In [2]: cnn = psycopg2.connect('')
[16529] psyco_connect: dsn = '', async = 0
[...]
[16529] connection_setup: good connection object at 0x7f05e3c5e2d0, refcnt = 1

In [3]: del cnn
[16529] conn_close: PQfinish called
[16529] connection_dealloc: deleted connection object at 0x7f05e3c5e2d0, refcnt = 0
```

I was wondering if there isn't some more subtle behaviour that changed somehow.

I'll close this bug, but please do let me know if you find something. Cheers!

**Closed by dvarrazzo** 2019-04-09 00:51 UTC
