### ISSUE TITLE
psycopg2.OperationalError: received invalid response to GSSAPI negotiation

### ISSUE THREAD

**Issue by markussv** [psycopg/psycopg2#1084] opened 2020-04-16 05:46 UTC
I've run into problems using sqlalchemy  and psycopg2 2.8.5 connecting to a Greenplum postgres database (fairly old, v.8.2, I think). When I call sqlalchemy.create_engine(), I get the error:

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) received invalid response to GSSAPI negotiation

This error disappears when I 'downgrade' to psycopg2 2.8.4; it also seems to be working fine with v2.7. A colleague more knowledgeable in Python and software development in general suggested 
that changes in response to  https://github.com/psycopg/psycopg2/issues/1019 could have something to do with it. I'm using Python 3.7.

**Comment by dvarrazzo** [comment] 2020-04-16 07:47
I doubt the two are related.

Are you using windows or another os? are you using psycopg2 or psycopg2-binary?

Thank you

**Comment by dvarrazzo** [comment] 2020-04-16 07:55
It might also be useful to know what libpq library is your code using. You can get this info with:

```python
>>> import psycopg2
>>> psycopg2.__libpq_version__
120002
>>> psycopg2.extensions.libpq_version()
120002
```

the first is the library psycopg was built with, the second is the dynamic library currently loaded.

**Comment by markussv** [comment] 2020-04-29 13:08
Sorry for being a bit slow to answer. I'm using psycopg2 on Windows 10 (Anaconda)

Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MSC v.1916 64 bit (AMD64)] on win32

For the working version I have:

`>>> import psycopg2`
`>>> psycopg2.__libpq_version__`
`110002`
`>>> psycopg2.extensions.libpq_version()`
`110002`
`>>> psycopg2.__version__`
`'2.8.4 (dt dec pq3 ext lo64)'`

and for the one that doesn't:

`>>> import psycopg2`
`>>> psycopg2.__libpq_version__`
`120002`
`>>> psycopg2.extensions.libpq_version()`
`120002`
`>>> psycopg2.__version__`
`'2.8.5 (dt dec pq3 ext lo64)'`

**Comment by dvarrazzo** [comment] 2020-04-29 14:35
It might be worth asking postgres people if something changed across the libpq versions shipped with 11 and 12 in relation with GSSAPI.

[PG 12 news](https://www.postgresql.org/about/news/1976/) say "This release introduces both client and server-side encryption for authentication over GSSAPI interfaces". Maybe this has something to do with dropping older GSSAPI implementations?

You can try and ask to the postgres people if they are aware of differences in libpq 12 which may cause your problem. However it's not something we can fix in psycopg. I also see that 2.8.5 is actually packaged with libpq 11.5 so I don't know where your version 12 is coming from: probably from conda? Can you try and install the original psycopg2 package from pip and see if it makes a difference?

**Comment by dvarrazzo** [comment] 2020-05-04 12:38
Closing because I don't think you are using an official psycopg2 package and we have no idea how conda builds theirs. But if you know other details I'm happy to know. Official 2.8.5 build ships with libpq 11.5 as I had problems building with a later version on windows but that might be fixed in the future so this could become relevant.

**Closed by dvarrazzo** 2020-05-04 12:38 UTC

**Comment by musthusaini** [comment] 2020-06-15 22:41
psycopg2.OperationalError: received invalid response to GSSAPI negotiation: 
Getting above error. could you please help.

**Comment by dvarrazzo** [comment] 2020-06-16 06:25
@musthusaini Maybe, if you care specifying what OS are you on, what version of psycopg2 are you using, what database are you connecting to, and a few other sensible info.

**Comment by davidanthonygardner** [comment] 2020-07-10 16:54
FWIW I ran into this issue today. The solution for me was to set the PGGSSENCMODE environment variable to `disable`.

The issue is caused by (I believe) a change in the kerberos auth settings in pg12. What happens is whenever a pg-pool or pgBouncer instance is proxying for Greenplum or PostgreSQL, kerberos (again speculating a bit here) believes the proxy to be performing a man-in-the-middle attack.

My setup:
psycopg2 2.8.5
python-2.7.13
Centos 7.6.1810

```
>>> import psycopg2
>>> psycopg2.__libpq_version__
120002
>>> psycopg2.extensions.libpq_version()
120002
>>> 
```

**Comment by thinkinds** [comment] 2021-09-30 01:11
> It might be worth asking postgres people if something changed across the libpq versions shipped with 11 and 12 in relation with GSSAPI.
> 
> [PG 12 news](https://www.postgresql.org/about/news/1976/) say "This release introduces both client and server-side encryption for authentication over GSSAPI interfaces". Maybe this has something to do with dropping older GSSAPI implementations?
> 
> You can try and ask to the postgres people if they are aware of differences in libpq 12 which may cause your problem. However it's not something we can fix in psycopg. I also see that 2.8.5 is actually packaged with libpq 11.5 so I don't know where your version 12 is coming from: probably from conda? Can you try and install the original psycopg2 package from pip and see if it makes a difference?

The same problem solved by installing from pip, thanks.

**Comment by JakovGlavac** [comment] 2024-09-20 10:06
> FWIW I ran into this issue today. The solution for me was to set the PGGSSENCMODE environment variable to `disable`.
> 
> The issue is caused by (I believe) a change in the kerberos auth settings in pg12. What happens is whenever a pg-pool or pgBouncer instance is proxying for Greenplum or PostgreSQL, kerberos (again speculating a bit here) believes the proxy to be performing a man-in-the-middle attack.
> 
> My setup: psycopg2 2.8.5 python-2.7.13 Centos 7.6.1810
> 
> ```
> >>> import psycopg2
> >>> psycopg2.__libpq_version__
> 120002
> >>> psycopg2.extensions.libpq_version()
> 120002
> >>> 
> ```

You can just set env using the os lib:
```python
import psycopg2
import os

os.environ['PGGSSENCMODE'] = 'disable'
conn = psycopg2.connect(...)
```

**Comment by wangquanqing** [comment] 2024-10-07 04:49
> > FWIW：我今天遇到了这个问题。对我来说，解决方案是将 PGGSSENCMODE 环境变量设置为 。`disable`
> > 该问题是由（我相信）pg12 中 kerberos 身份验证设置的更改引起的。发生的情况是，每当 pg-pool 或 pgBouncer 实例代理 Greenplum 或 PostgreSQL 时，kerberos（这里再次推测一下）认为代理正在执行中间人攻击。
> > 我的设置：psycopg2 2.8.5 python-2.7.13 Centos 7.6.1810
> > ```
> > >>> import psycopg2
> > >>> psycopg2.__libpq_version__
> > 120002
> > >>> psycopg2.extensions.libpq_version()
> > 120002
> > >>> 
> > ```
> 
> 你可以只使用 os lib 设置 env：
> 
> ```python
> import psycopg2
> import os
> 
> os.environ['PGGSSENCMODE'] = 'disable'
> conn = psycopg2.connect(...)
> ```

I have the same problem, and now it has been solved. Thank you

**Comment by TeemuKoivisto** [comment] 2024-11-18 16:31
I somehow had this same error `received invalid response to GSSAPI negotiation: S` when trying to connect to Supabase postgres instance with psql on macOS 15. The error appeared immediately after upgrading from postgres 14 to postgres 15.9. Upgrading all the way to 17 then fixed it.
