### ISSUE TITLE
Using psycopg2-binary for production build for Python 3.9

### ISSUE THREAD

**Issue by optionriskdoctor-app** [psycopg/psycopg2#1283] opened 2021-05-28 10:29 UTC
We have to use Python 3.9 as we require some of the newer enhancements made in Python 3.9. But the issue is psycopg2 is not working on our developmental machines and one of the possible reasons is maybe psycopg2 supports only till Python 3.8. We have tried everything but unable to import psycopg2 in our .py module, though its successfully getting installed via pip. now the question is can we use psycopg2-binary for production?

**Comment by dvarrazzo** [comment] 2021-05-28 10:52
No, psycopg2 supports Python 3.9 alright.

The use of the -binary packages in production is discouraged because in the past they proved unreliable in multithread environments. This might have been fixed in more recent versions but I have never managed to reproduce the failure.

Anyway, I think your problem is somewhere else, not in Python 3.9.

**Comment by optionriskdoctor-app** [comment] 2021-05-28 10:57
But trying since yesterday and did everything but still am unable to install psycopg2. psycopg2 gets downloaded but when trying to import it says ModuleNotFoundError: No module named 'psycopg2'.

**Closed** 2021-05-28 11:51 UTC
