### ISSUE TITLE
"SSL SYSCALL error: Connection timed out" error returned as DatabaseError instead of OperationalError

### ISSUE THREAD

**Issue by dhoffman34** [psycopg/psycopg2#1496] opened 2022-09-19 14:47 UTC
**Please complete the following information:**
- OS: Alpine Linux
- Psycopg version: 2.9.3
- Python version: 3.9.10

**Describe the bug**

We occasionally get "SSL SYSCALL error: Connection timed out" errors from our database. We noticed that `psycopg2` maps these to `DatabaseError`, but it looks like this should be `OperationalError`: https://peps.python.org/pep-0249/#operationalerror

**Comment by dvarrazzo** [comment] 2022-09-19 15:26
Yes, it makes sense. The problem is that upon errors like these (connection lost) we don't get any error code information (because the error is generated by the client library, not the server). Client errors are hard to tell apart, owing to their lack of SQLSTATE code: relying on the error message is not a robust solution, so we have to use the most generic class available.

Maybe it would be ok to generate an OperationalError upon every error that comes without a SQLSTATE, and this would even be backward compatible because OperationalError is a DatabaseError subclass; however there would be no way back: if we start associating OperationalError to exceptions that are not such, it would be non-backward-compatible to make them DatabaseError or a different class.

Let's give it a thought...

**Comment by dvarrazzo** [comment] 2022-09-19 15:53
I also see that other paths actually return OperationalError. For instance, restarting the server, I get:

```
In [11]: cur.execute("select 1")                                                                                     
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-11-8c7388a6b069> in <module>
----> 1 cur.execute("select 1")

OperationalError: terminating connection due to administrator command
SSL connection has been closed unexpectedly
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

similarly, if I connect via a proxy and close connection half way:

```
OperationalError: SSL SYSCALL error: EOF detected
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

How do you obtain a `DatabaseError`?

**Comment by dhoffman34** [comment] 2022-09-19 19:53
@dvarrazzo, 

> Yes, it makes sense. The problem is that upon errors like these (connection lost) we don't get any error code information (because the error is generated by the client library, not the server). Client errors are hard to tell apart, owing to their lack of SQLSTATE code: relying on the error message is not a robust solution, so we have to use the most generic class available.

Ah, interesting.

> How do you obtain a DatabaseError?

Unfortunately I'm not sure how to reliably reproduce this. It is an error we occasionally get in production, but I'm not sure how to actually trigger it. I should say too that what we log is actually a Django error, but I can see that it's wrapping `psycopg2`'s `DatabaseError`.

**Comment by dvarrazzo** [comment] 2022-09-19 21:02
I tried to reproduce timeouts in other ways. For instance setting a session timeout:

```
In [8]: cur.execute("set idle_session_timeout to '5s'")                                                                                                                                                                                      

In [9]: import time                                                                                                                                                                                                                          

In [10]: time.sleep(5)                                                                                                                                                                                                                       

In [11]: cur.execute("select 1")                                                                                                                                                                                                             
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-11-8c7388a6b069> in <module>
----> 1 cur.execute("select 1")

OperationalError: terminating connection due to idle-session timeout
SSL connection has been closed unexpectedly
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

I consistently receive OperationalError upon such failures. This one is still pretty polite (the server manages to send the client a message about the disconnection reason) but it's still an error without sqlstate - as such it is managed using a fallback exception.

```
In [12]: import sys                                                                                                                                                                                                                          

In [13]: exc = sys.last_value                                                                                                                                                                                                                

In [14]: exc                                                                                                                                                                                                                                 
Out[14]: psycopg2.OperationalError('terminating connection due to idle-session timeout\nSSL connection has been closed unexpectedly\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')

In [15]: exc.diag.sqlstate                                                                                                                                                                                                                   

In [16]: exc.pgcode                                                                                                                                                                                                                          

In [17]:  
```

The most impolite disconnection (the one causing the `SSL SYSCALL error`, which can be reproduced by taking down a connection proxy, hence giving no chance to the server to send messages) still raises an OperationalError.

So I'm not sure how you get a DatabaseError. Maybe it's Django interfering?

I will have to close this here, because I can't reproduce the issue. If you find a way to reproduce it I'm happy to investigate further.

**Closed by dvarrazzo** 2022-09-19 21:02 UTC

**Comment by dhoffman34** [comment] 2022-09-19 23:59
Sounds good, thank you for taking a look.

Good point that it may be Django interfering. In case anyone looks at this ticket in the future, here is the line from which the exception was thrown: https://github.com/django/django/blob/653a7bd7b7c2f7c3ffe6b22be53da1472c491474/django/db/backends/utils.py#L84

I'll update if we find a way to reproduce this.
