### ISSUE TITLE
windows pip install fails - version 2.9.5

### ISSUE THREAD

**Issue by aamster** [psycopg/psycopg2#1516] opened 2022-10-25 17:49 UTC
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Before opening this ticket, please confirm that:**
- [ ] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [ ] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [ ] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS: Microsoft Windows Server 2022
- Psycopg version: 2.9.5
- Python version: 3.8
- PostgreSQL version: unknown
- pip version 22.2.2  

pip Install fails with 
```
Failed to build psycopg2-binary
...
  LINK : fatal error LNK1181: cannot open input file 'libpq.lib'
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
  [end of output]
```

pip install version 2.9.4 works.

**Comment by dvarrazzo** [comment] 2022-10-25 18:15
Try again now. See #1514. Dupe of #1515.

**Closed by dvarrazzo** 2022-10-25 18:15 UTC
