### ISSUE TITLE
2.7.7 to 2.8.1 - RealDictRow.items() behavior change

### ISSUE THREAD

**Issue by alexandersoto** [psycopg/psycopg2#891] opened 2019-04-08 23:48 UTC
When upgrading from 2.7.7 to 2.8.1 I noticed that `RealDictRow` does not behave the same. Previously, I was able to call `items()` on a `RealDictRow` and it'd return `(key, value)` tuples, like a Python dict.

In 2.8.1 it instead returns a `(RealDictRow, ListOfKeys)` as the first tuple. The remaining items are `(key, value)` pairs as expected.

**Comment by dvarrazzo** [comment] 2019-04-09 00:00
I know that guy: it's a bug I introduced by mistake to fix #886. It's already fixed in master (4058f363d69159b7c0193b6bd873aa0ee0621a89) and will be released in 2.8.2.

Thus bug should affect you only if you have repeated fields name in your query. Is this the case? If not can you post the query generating the wrong values? Thank you.

**Comment by alexandersoto** [comment] 2019-04-09 00:21
I saw those issues but didn't think it was the same problem.

There are no repeated rows, but there is an `*`:
```sql
SELECT users.*,
       companies.plan,
       companies.domain,
       companies.uuid       AS company_uuid,
       companies.name       AS company_name,
       companies.created_at AS company_created_at
FROM users INNER JOIN companies
     ON users.company_uuid = companies.uuid
WHERE  users.idp = %s AND users.idp_id = %s
```

`uuid` and `created_at` are columns on both `users` and `companies`. That's why the `companies` column have aliases. Could that be causing the issue?

**Comment by dvarrazzo** [comment] 2019-04-09 00:38
Yes, this is a duplicate of #884, the fix will be released in 2.8.2.

Your query has an undefined behaviour: you have two fields called the same way, what a name mapping would return is totally arbitrary. This bug affect only those queries which are broken anyway, so yes, a fix will be released soon, butfirst I'll wait a couple of days for feedback from other issued before packing 2.8.2.

**Closed by dvarrazzo** 2019-04-09 00:38 UTC

**Comment by dvarrazzo** [comment] 2019-04-09 00:42
Sorry, I read your comment wrongly, but please do check about your query: the fields causing problems are not the aliased ones but some in the `*` which isn't aliased.

So what does `[d[0] for d in curs.description]` return?

**Comment by alexandersoto** [comment] 2019-04-09 00:50
Ah, you are correct, there was a repeated column. Looks like `company_uuid` is also on the `users` table. Getting rid of the ambiguous `companies.uuid AS company_uuid` line fixes it!

Sorry about that. And thanks for all your work on such a great library :)
