### ISSUE TITLE
linking to /usr/local/lib/libpq.x regardles of /usr/bin/pg_config

### ISSUE THREAD

**Issue by naox** [psycopg/psycopg2#378] opened 2015-12-02 00:13 UTC
```
user@sv1 [/home/user/a/psycopg2-2.5.5/build/lib.3.5]# python
Python 3.5.0 (default, Nov 17 2015, 22:55:47)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-50)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>>

user@sv1 [/home/user/a/psycopg2-2.6/build/lib.3.5]# python
Python 3.5.0 (default, Nov 17 2015, 22:55:47)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-50)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>>

user@sv1 [/home/user/a/psycopg2-2.6.1/build/lib.3.5]# python
Python 3.5.0 (default, Nov 17 2015, 22:55:47)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-50)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/a/psycopg2-2.6.1/build/lib.3.5/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: /home/user/a/psycopg2-2.6.1/build/lib.3.5/psycopg2/_psycopg.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PQinitOpenSSL

```

bug is present in 2.6.1 but not in 2.6.0 or 2.5
os: centos 5.3
postgresql: tested against 9.4.4 and 9.2.1

**Comment by dvarrazzo** [comment] 2015-12-02 13:57
It was probably compiled on a different machine with a libpq version newer than the one available on the machine you are trying to run it. @wulczer may have more info.

**Comment by dvarrazzo** [comment] 2015-12-02 14:02
In `psycopgmodule.c` there is

```
#if PG_VERSION_NUM >= 80400
        PQinitOpenSSL(1, 0);
#endif
```

which seems suggesting you are trying to run psycopg with libpq 8.3 or earlier, unless the test is broken. This is a compile-time testing, meaning that when compiled libpq was more advanced than now that you are running it. If you compile it with libpq 8.3 the instruction wouldn't be included.

**Comment by wulczer** [comment] 2015-12-02 14:29
@dvarrazzo that's right, the problem is that psycopg got compiled against new libpq, but is being run on a system with older libpq.

@naox you need to either install correct libpq on the system, or rebuild against an older libpq version. Can you paste the output of `ldd /home/user/a/psycopg2-2.6.1/build/lib.3.5/psycopg2/_psycopg.cpython-35m-x86_64-linux-gnu.so` ? Maybe it's picking up libpq from the wrong location.

**Comment by naox** [comment] 2015-12-02 14:52
If compiled with make or python setup.py build_ext its not dynamic executable
```
user@sv1 [/home/user/a/psycopg2-2.6.1/build/lib.linux-x86_64-3.5/psycopg2]# ldd _psycopg.cpython-35m-x86_64-linux-gnu.so
ldd: warning: you do not have execution permission for `./_psycopg.cpython-35m-x86_64-linux-gnu.so'
        not a dynamic executable
```
but if compiled with python setup.py install (or easy_install , pip) it is linked against wrong (old)  libpq
        linux-vdso.so.1 =>  (0x00007ffea7d5d000)
        libpq.so.5 => /usr/local/lib/libpq.so.5 (0x00007fdff9d1b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdff9aff000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fdff97a6000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fdff956e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdffa167000)
so the problem is that installation/linking of psycopg2 does not use /usr/bin/pg_config to check proper location of ligpq

```
user@sv1 [/home/user]# /usr/bin/pg_config
BINDIR = /var/postgresql-9.4.4/bin
DOCDIR = /var/postgresql-9.4.4/share/doc
HTMLDIR = /var/postgresql-9.4.4/share/doc
INCLUDEDIR = /var/postgresql-9.4.4/include
PKGINCLUDEDIR = /var/postgresql-9.4.4/include
INCLUDEDIR-SERVER = /var/postgresql-9.4.4/include/server
LIBDIR = /var/postgresql-9.4.4/lib
PKGLIBDIR = /var/postgresql-9.4.4/lib
LOCALEDIR = /var/postgresql-9.4.4/share/locale
MANDIR = /var/postgresql-9.4.4/share/man
SHAREDIR = /var/postgresql-9.4.4/share
SYSCONFDIR = /var/postgresql-9.4.4/etc
PGXS = /var/postgresql-9.4.4/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/var/postgresql-9.4.4' '--with-perl' '--with-libxml' '--with-libxslt' '--with-openssl' 'CFLAGS=-O3' 'LDFLAGS=-L/usr/openssl-1.0.1p/lib'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O3
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -L/usr/openssl-1.0.1p/lib -Wl,-rpath,'/var/postgresql-9.4.4/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lssl -lcrypto -lz -lreadline -ltermcap -lrt -lcrypt -ldl -lm
VERSION = PostgreSQL 9.4.4
```

Sure, I could probably append CPPFLAGS and LDFLAGS but this should be done automaticly based on /usr/bin/pg_config so normal users don't have such problems

**Comment by dvarrazzo** [comment] 2015-12-02 16:00
The bug is present in 2.6.1 because that's when the use of `PQinitOpenSSL` was introduced.

The problem is not that psycopg doesn't find the right pg_config: it's rather that ld of your operative system doesn't... how to blame it? To be sure, check the `PG_VERSION_NUM` variables passed on command line to gcc by setup.py. But then, regardless what you compile it against, at runtime `ldd` just finds the library in `/usr/local/lib/` and uses that.

You can maybe fix it by exporting `LD_LIBRARY_PATH=/var/postgresql-9.4.4/lib` in the environment running Python. My two observations are:

- you are officially in dll hell, albeit on Linux. If you don't remove the libpq in `/usr/local/lib/` you are doomed to many a sleepless nights.

- you have the lib you wish to link at runtime in a location the OS doesn't know about, and one you don't wish to link in a standard location. This is not psycopg bug, nor a problem psycopg can fix, hence closing this bug.

**Closed by dvarrazzo** 2015-12-02 16:00 UTC

**Comment by naox** [comment] 2015-12-02 17:07
Bug is not invalid but oh well. psycopg2 compilation-configure process does not not link against postgresql libs shown by output of /usr/bin/pg_config. Probably missing some flags at compile time or some are not set according to /usr/bin/pg_config

It has nothing to do with "dll hell" as every software should allow compilation against libs in other that system directories (and in this case libs specified by /usr/bin/pg_config output). Postgresql as everysoftware supports installation with --prefix and just because of that provides pg_config so software depending on it can use it to locate libs in non standard location. Its obvious that sooner or later libs in system dirs will be out of date. Removing those is still very bad idea.

**Comment by wulczer** [comment] 2015-12-02 17:15
@naox psycopg tries to find the correct `pg_config` when you compile and you can also override the path via a command line switch, see here for details:

https://github.com/psycopg/psycopg2/blob/fe4cb0d49353f56328b9981a5140ecda65e972b4/setup.py#L96

How did you compile psycopg on this system?

**Comment by naox** [comment] 2015-12-02 17:26
@wulczer psycopg finds and "uses" proper pg_config, however it does not make good on its output and does link to /usr/local/lib/libpq.so.5 instead of libpg.so in dir provided by output of /usr/bin/pg_config (LIBDIR = /var/postgresql-9.4.4/lib). There is need for a way to disable linking to /usr/local/lib and link to LIBDIR provided by output of /usr/bin/pg_config

**Comment by dvarrazzo** [comment] 2015-12-02 17:36
Use static linking (untested since 2001 I believe).

**Comment by dvarrazzo** [comment] 2015-12-02 17:38
There is no way that I know to tell `ld` to link at runtime to a library in a specific dir. If you find one suggest it. If you cannot just compile psycopg using the *old* pg_config version.

**Comment by wulczer** [comment] 2015-12-02 18:32
@dvarrazzo is right, it's just how the linux dynamic linker works. If you need to change its behaviour, either configure it through `/etc/ld.so.conf` or set `LD_LIBRARY_PATH` or use `-Wl,-rpath` when building psycopg.

Once the library is built, it's up to the system's dynamic linker to resolve it at runtime, nothing psycopg can do here.

**Comment by naox** [comment] 2015-12-02 19:03
@wulczer psycopg is not only a c code but also a makefile and configure code and it should provide ways to compile it according to pg_config LIBDIR  
Like I said before so far I was unable to use LD_LIBRARY_PATH to specify custom libpq.so location. If it were working then psycop2 configure process should set it according to pg_config output during compile time. I will keep looking for proper compiler flags but I have little experience in that field. There has to be a way to do it as basicly all software provides similar compile time functionality. I'll try to look into configure and Makefile of other software but like i said this should be done by someone with experience.

**Comment by dvarrazzo** [comment] 2015-12-02 23:54
@naox: now you are becoming borderline troll.

If your OS is set up so that `ld` finds libpq version 8.3 installed (obsolete for at least 5 years), then:

- either you complile psycopg with pg_config 8.3 or
- you compile psycopg statically, see `setup.ini`.

So you already have two different ways to make psycopg work on your messed up obsolete system, and you keep blathering on of "there has to be a way to do it as basicly all software provides similar compile time functionality" Here they are. Do you want more? Either you propose a solution with a patch whose implementation transcends both Jan and my knowledge of how Linux works, hence we cannot provide, or please stop saying nonsense. 

Psycopg has been compiled exactly the way it was requested: `LIBDIR` was respected at compile time. You asked to use a 9.4 pg_config and the 9.4 support has been compiled in. If *at runtime* you are not able to provide the dynamic linker (which is not part of psycopg) information of where the libpq 9.4 library is (which is not part of psycopg) in your non-standard file system (guess: not a part of psycopg) it is *your* problem.

**Comment by fogzot** [comment] 2015-12-03 08:44
The right way to solve this is to use `-rpath`. Modifying `setup.py` to add an argument to pass `-rpath` to the linker should be quite easy but `-rpath` IS EVIL. If you need to use it, your system is broken anyway (libraries are not where the dynamic linker looks for them and this is solved much better using `LD_LIBRARY_PATH` than fiddling with the binaries.

**Comment by naox** [comment] 2015-12-04 03:44
thanks fogzot for answer. As you say -  rpath is solution - used by all software as I see in many configure scripts that allow specifying lib location as argument.

I don't agree that system containing many versions of software (binaries and libraries) (at any location) is broken and since postgresql creators made pg_config script to adress just that (script to find out custom location of postgresql, its libs) I assume they think similary.

As is stands now psycopg2 compilation process does not respect LIBDIR from pg_config output (does not set rpath based on it).

**Comment by wulczer** [comment] 2015-12-04 09:45
Ah, interesting, so the issue is that you argue that psycopg should take `LDFLAGS` and `CFLAGS` from `pg_config` output.

I'm not sure that would be correct, honestly. psycopg is a Python extension, so it needs `LDFLAGS` and `CFLAGS` provided by setuptools and simply merging in PostgreSQL backend `LDFLAGS` could not be the right thing to do.

The output of `pg_config` is not supposed to tell you how to compile things that depend on PostgreSQL, but to provide information about how Postgres was compiled and installed. In your specific situation, you compiled the server with `-rpath` so you should just pass that same `rpath` when building pscopg.

Doesn't this work?

```
CPPFLAGS=-I/var/postgresql-9.4.4/include LDFLAGS="-L/var/postgresql-9.4.4/lib, -Wl,-rpath,'/var/postgresql-9.4.4/lib'" python setup.py install
```

**Comment by fogzot** [comment] 2015-12-04 10:26
A system with multiple versions of PostgreSQL is perfectly fine, but having multiple versions of libpq is bad. libpq is backward compatible and knows how to connect to old versions of the backend so there is no need to have multiple copies of it. Just put the newest libpq in a place where the dynamic linker can find it and compile psycopg against it.

The case for `-rpath` is when you need to keep multiple *backward incompatible* versions of the same library. IMHO any other use is trying to fix the wrong problem with the wrong tool.

Anyway, have a look at this patch (just build with the new `--use-rpath` option):

https://github.com/fogzot/psycopg2/tree/feature-rpath

**Comment by wulczer** [comment] 2015-12-04 10:31
FWIW I'm mildly -1 on adding an option like that, since people who want to customise `LDFLAGS` can already do that via env vars and it gives them more flexibility. Special-casing `rpath` doesn't feel that useful.

**Comment by fogzot** [comment] 2015-12-04 10:37
The option already exists in setup.py and its called, guess what, `--rpath`. But as many other things in setuptools it is broken. I just added a workaround to enable it and pass the correct library path.

**Comment by wulczer** [comment] 2015-12-04 12:10
Oh, OK, I guess my setuptools-foo is not strong enough :)

**Comment by naox** [comment] 2015-12-04 17:00
>> A system with multiple versions of PostgreSQL is perfectly fine, but having multiple versions of libpq is bad. libpq is backward compatible and knows how to connect to old versions of the backend so there is no need to have multiple copies of it. Just put the newest libpq in a place where the dynamic linker can find it and compile psycopg against it.

Good to know but You sure put a lot of trust in developers of software in them keeping backward compatibility intact - instead of using completly separate binary/library sets. Not a good practice in a long run imho.

**Comment by dvarrazzo** [comment] 2015-12-04 17:58
Why isn't static linking a better option?
