### ISSUE TITLE
Range type comparison operators return unexpected results

### ISSUE THREAD

**Issue by unklphil** [psycopg/psycopg2#376] opened 2015-11-11 11:45 UTC
The range types' `<`, `>` and consequently `<=` and `>=` comparison operators return unexpected results when comparing Ranges to non-Range objects. E.g.:

```python
from psycopg2.extras import NumericRange
nr = NumericRange(1, 10)

from psycopg2.extras import NumericRange
nr = NumericRange(1, 10)

# int comparison
print(nr < 100)  # False
print(nr > 100)  # True
print(nr <= 100)  # False
print(nr >= 100)  # True

# float comparison
print(nr < 10.0)  # False
print(nr > 10.0)  # True
print(nr <= 10.0)  # False
print(nr >= 10.0)  # True

# str comparison
print(nr < 'foobar')  # True
print(nr > 'foobar')  # False
print(nr <= 'foobar')  # True
print(nr >= 'foobar')  # False

# bool comparison
print(nr < False)  # False
print(nr > False)  # True
print(nr <= False)  # False
print(nr >= False)  # True
print(nr < True)  # False
print(nr > True)  # True
print(nr <= True)  # False
print(nr >= True)  # True
```

In all these cases, one would expect a `TypeError` to be raised with a message like `TypeError: can't compare NumericRange to int`.

The problem seems to stem from **returning** `NotImplemented` (which gets cast to a boolean) instead of **raising** `TypeError`. 

See [here](https://github.com/psycopg/psycopg2/blob/fe4cb0d49353f56328b9981a5140ecda65e972b4/lib/_range.py#L142) and [here](https://github.com/psycopg/psycopg2/blob/fe4cb0d49353f56328b9981a5140ecda65e972b4/lib/_range.py#L166).

**Comment by dvarrazzo** [comment] 2015-11-11 12:38
[NotImplemented](https://docs.python.org/2/library/constants.html#NotImplemented) is the constant to return in the [rich comparison protocol](https://www.python.org/dev/peps/pep-0207/) when one type doesn't know how it sorts with the other. What Python does with it is not really Psycopg concern. More specifically what you have found is a known Python 2 implementation wart [fixed in Python 3](https://docs.python.org/3.0/whatsnew/3.0.html#ordering-comparisons).

Builtin types implementing the rich comparison protocol behave like `Range` do. Strings, for example:

    In [12]: 'a'.__lt__(10)
    Out[12]: NotImplemented

If both objects return `NotImplemented`, Python 2 decides to do some arbitrary nonsense like comparing the pointers. Python 3 raises `TypeError` if neither of the type knows the other:

```
In [3]: r = psycopg2.extras.Range(10,20)

In [5]: r.__lt__('a')
Out[5]: NotImplemented

In [6]: 'a'.__lt__(r)
Out[6]: NotImplemented

In [7]: r < 'a'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-8fe969dd754d> in <module>()
----> 1 r < 'a'

TypeError: unorderable types: Range() < str()
```

It's not a psycopg bug: Python 2 has always been a bit bonkers comparing heterogeneous types.

**Closed by dvarrazzo** 2015-11-11 12:38 UTC

**Comment by unklphil** [comment] 2015-11-11 15:30
Thanks for your help, and thank you for maintaining this package!

> Python 2 has always been a bit bonkers comparing heterogeneous types

Just another reason to speed up our transition to Python 3.

We actually came across this problem when trying to implement functions for the [Postgres range operators](http://www.postgresql.org/docs/current/static/functions-range.html#RANGE-OPERATORS-TABLE). 

Are there any plans for implementing them on the Range classes? As classmethods not operators, e.g. `Range.intersect(other)`.

**Comment by dvarrazzo** [comment] 2015-11-11 19:07
I originally considered implementing them, and eventually preferred to leave them out. I can't remember exactly why; unfortunately the reasoning doesn't appear in git history. One issue I remember was that, creating a range over strings, postgres and python were giving different results, because of the collation. I can't remember if this was the only issue found (which would have probably been a bit throwing away the baby out with the bathwater: builtin ranges would have probably worked just fine) but I clearly remember it an amusing source of WTF's. Actually for the same reason ranges didn't even have ordering: it was added as per #10.

Looking at the docs:

> This Python type is only used to pass and retrieve range values to and from PostgreSQL and doesn’t attempt to replicate the PostgreSQL range features: it doesn’t perform normalization and doesn’t implement all the operators supported by the database.

reminds me that another source of possible confusion could have been caused by the ranges not being normalized in Python (in order to do which you need to introduce in python the concept of discrete ranges too, further complicating the objects). Doable, but it starts being a little bit too semantically loaded for a database driver: without normalization you may end up easily with operators behaving differently between Python and Postgres; introducing it you may end up with subtle alteration of the data returned by the database (with eyebrows raising at sky levels and a chorus of tsk-tsk-these-drivers-that-try-to-do-too-much...)

Are you thinking about writing operators like `Range.does_not_extend_to_the_right_of()`? Because, you know... :sob:

So yeah, you have a sort of mild discouragement from me here, but not a veto: I would consider merging a well coded, well documented, well tested patch, as long as **perfectly** consistent with the database behaviour.

Of course you are totally free to write an external pip-able `psycopg_range_ops` module implementing `psycopg_range_ops.does_not_extend_to_the_right_of(r1, r2)` :) Or monkeypatching `Range`, that's always cool :P Or subclassing it, if you don't fancy the thrill of a well undetermined program: `register_range()` can take the python class to cast into so it would happily accept your `RangeWithOperator` subclass.

**Comment by unklphil** [comment] 2015-11-12 08:59
Thanks for the detailed reply, and I completely understand your point about the results being inconsistent with the database.

> Are you thinking about writing operators like Range.does_not_extend_to_the_right_of()? Because, you know... :sob:

Haha, I was thinking more along the lines of [Django's range lookup](https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/fields/#comparison-functions) names, i.e. `Range.does_not_extend_to_the_right_of()` would be `Range.not_gt()`. Obviously this would need to be well documented to explain that `not_gt` is not the same as `lte`.

> I would consider merging a well coded, well documented, well tested patch

We'll see what we end up with, we probably won't need all the the operators' functionality for what we're using it for, so we'll just implement what we need for now, but we might one day submit a pull request (or create our own package).
