### ISSUE TITLE
ImportError of dynamic libs at runtime

### ISSUE THREAD

**Issue by florianm93** [psycopg/psycopg2#411] opened 2016-02-22 09:40 UTC
I upgraded my Postgres Version on my Mac OS Device. When I tried to run my project, i get the following error 
`ImportError: dlopen(/project-path/.venv/lib/python3.5/site-packages/psycopg2/_psycopg.cpython-35m-darwin.so, 2): Library not loaded: /Applications/Postgres.app/Contents/Versions/9.4/lib/libssl.1.0.0.dylib
  Referenced from: /project-path/.venv/lib/python3.5/site-packages/psycopg2/_psycopg.cpython-35m-darwin.so
  Reason: image not found`

My prior Version of the Postgres.app was 9.4, now 9.5. I fixed this ImportError with uninstalling and installing the psycopg2 package (with pip). So it looks like you only test on install where Postgres is installed and not at runtime? Maybe you can enhance your install routine, e.g. by replacing `[...]/Versions/9.4/lib` with `[...]/Versions/latest/lib`, which is more common way I think (for most reasons).

Thanks so far, Florian

**Comment by dvarrazzo** [comment] 2016-02-22 11:31
No: we don't *test* at runtime where postgres is installed: we *compile* psycopg and then let the dynamic linker and the OS find the libraries. This behaviour of Mac OS is new for me, but not surprising at all: Mac OS breaks building or linking at every single version.

The path of the library we compile against is the one returned by pg_config. If you think pg_config is returning the wrong value you should contact PostgreSQL authors and hear from them if the situation can be improved.

Closing because psycopg is working as intended: compiling against what suggested by pg_config and then letting the OS finding the dynamic library the native way.

**Closed by dvarrazzo** 2016-02-22 11:31 UTC
