### ISSUE TITLE
Mogrify freezes when called on psycopg2.Binary from different process

### ISSUE THREAD

**Issue by ajyeager** [psycopg/psycopg2#810] opened 2018-11-14 20:48 UTC
I included a minimal example to reproduce this issue.  Basically when calling mogrify on a bytea type, if a different process constructed the pyscopg2.Binary object, the program freezes on mogrify.  Tested this is 2.7.6.1 and 2.7.6

```python
import psycopg2
from multiprocessing import Pool


def type_check(x):
    return type(x)

def target(x):
    with psycopg2.connect(host="127.0.0.1", user="postgres",password="postgres") as con:
        with con.cursor() as cur:
            return cur.mogrify("%s", (x,))
        
def post_convert_target(x):
    with psycopg2.connect(host="127.0.0.1", user="postgres",password="postgres") as con:
        with con.cursor() as cur:
            return cur.mogrify("%s", (psycopg2.Binary(x),))

pool = Pool(1);

example = 'test'
example_binary = psycopg2.Binary(example)
example, example_binary


#Show same process works as expected
print apply(type_check, (example,))
print apply(post_convert_target, (example,))

print apply(type_check, (example_binary,))
print apply(target, (example_binary,))


#Show different process works when the 2nd process converts to psycopg2.Binary itself
print pool.apply(type_check, (example,))
print pool.apply(post_convert_target, (example,))

#Show the passed object is still a psycopg2.Binary type in the 2nd process
print pool.apply(type_check, (example_binary,))

#This freezes the program
print pool.apply(target, (example_binary,))
```

**Comment by dvarrazzo** [comment] 2019-02-27 01:32
Looking at a strace session, one of the child processes dies of a segfault on psycopg/adapter_binary.c:76

```c
    if (PyObject_CheckBuffer(self->wrapped)) {
```

it looks like the pool doesn't notice, but then some other process gets stuck in a `read()` from a pipe.

Running the same under Python 3, the program stops with an error because `Binary` is not picklable.

```
Traceback (most recent call last):
  File "pool-multiproc.py", line 45, in <module>
    print(pool.apply(target, (example_binary,)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 281, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 450, in _handle_tasks
    put(task)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle psycopg2.extensions.Binary objects
```

What is weird is that `Binary` is not picklable in Py2 either:

```
>>> import psycopg2
>>> import pickle
>>> pickle.dumps(psycopg2.Binary('x'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle Binary objects
```

so it seems we either don't raise a proper exception upon pickling in some exotic fashion (none of which I can spot looking at the processing package) or the py2 processing swallows the exception and sends down the pipe data that make the child segfault.

**Comment by dvarrazzo** [comment] 2019-02-27 02:21
Oh but in Py2:

```
>>> cPickle.dumps(psycopg2.Binary('x'), cPickle.HIGHEST_PROTOCOL)
'\x80\x02cpsycopg2.extensions\nBinary\nq\x01)\x81q\x02.'
```

and sure enough:

```
>>> pickle.loads(pickle.dumps(psycopg2.Binary(b'x'), pickle.HIGHEST_PROTOCOL))
<psycopg2.extensions.Binary at 0x7fbec5cbec88>

>>> _.getquoted()
Segmentation fault (core dumped)
```

This is true for other adapters too (tested with Int).

This comes from

>>> b.__reduce_ex__(2)
(<function copy_reg.__newobj__>, (psycopg2.extensions.Binary,), None, None, None)

which is the implementation provided by `object`. In Py3 it raises the "can't pickle" exception.

So it seems the bug has been there forever; these objects can't be pickled (they shouldn't be picklable because if prepared they would have a pointer to the connection). The problem only manifests in Python 2, 3.6 has a sane behaviour. In order to fix it we should implement a dummy `__reduce_ex__()` for each single adapter. I think this will end up staying unfixed.

**Comment by dvarrazzo** [comment] 2019-02-27 02:28
Most likely caused by <https://bugs.python.org/issue8323>.

The issue was closed as "wontfix". I will follow the example, as Py2 has now just 10 months of life.

**Closed by dvarrazzo** 2019-02-27 02:28 UTC
