### ISSUE TITLE
uuid type and python sub interpreter + mod_wsgi

### ISSUE THREAD

**Issue by felipinbombin** [psycopg/psycopg2#776] opened 2018-09-24 18:15 UTC
Hi 😄 !

i had a problem with mod_wsgi related with uuid and sub interpreter, you can see it [here](https://github.com/GrahamDumpleton/mod_wsgi/issues/206#issuecomment-423244971). Why this is important for psycopg2? because i think it is related with the way psycopg2 load uuid library. The symptom is similar to this [issue] (https://github.com/psycopg/psycopg2/issues/52). 

If you need more information just ask 👍  thanks!

regards!

**Comment by dvarrazzo** [comment] 2018-09-24 19:03
Hi,

the problem with psycopg and Decimal was that the psycopg was importing the Python Decimal module in the C module init function: as such it was called only once, and not once per sub-interpreter. Further sub-interpreters would have created different Decimal classes, but psycopg would have still created the adapters map (the map from Python class to adaptation function to use) using the first Decimal class created, so Decimal instances created in other sub-interpreter would have failed the `isinstance()` test.

The solution was to move Decimal registration into the Python `__init__.py` so that new processes importing `psycopg2` get an adapters map with the local definition of the Decimal class.

The `uuid` module is imported at Python level by the `register_uuid()` function ([here](https://github.com/psycopg/psycopg2/blob/2_7_5/lib/extras.py#L643)). So I don't see it being affected by the same problem fixed in #52, assuming that every sub-interpreter calls `register_uuid()`, and I don't see a reason why it shouldn't (or how it could work without doing it...).

**Comment by dvarrazzo** [comment] 2018-11-16 17:10
Closing as it doesn't appear there is nothing we can or should do, because psycopg doesn't import/cache the uuid module in C (which was the cause of #52).

**Closed by dvarrazzo** 2018-11-16 17:10 UTC
