### ISSUE TITLE
psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication

### ISSUE THREAD

**Issue by bimcas** [psycopg/psycopg2#1313] opened 2021-06-28 10:48 UTC
**Environment**
Python version: 3.6.8
Patroni version: 2.0.2
PostgreSQL version: 12.7

**Describe the bug**
I used psycopg2-binary 2.8.6 version. After updating **psycopg2-binary** to **2.9.1** version I'm getting error messages in postgresql logs on nodes of Patroni/PostgreSQL cluster :

Jun 28 12:02:58 patroni[4817]: psycopg2.errors.InternalError: cannot execute SQL commands in WAL sender for physical replication
2021-06-28 10:25:28.754 UTC,"replication","",ERROR,XX000,"cannot execute SQL commands in WAL sender for physical replication",,,,,,,,,""
2021-06-28 10:25:29.760 UTC,"replication","",ERROR,XX000,"cannot execute SQL commands in WAL sender for physical replication",,,,,,,,,""
2021-06-28 10:25:29.761 UTC,"replication","",ERROR,XX000,"cannot execute SQL commands in WAL sender for physical replication",,,,,,,,,""

Despite the error in logs, all nodes are running in the cluster, I can failover.

**To Reproduce**
Update psycopg2-binary to 2.9.1.

Expected behavior
When I rollbacked psycopg2-binary to 2.8.6 version, I don't have suck error messages in patroni and postgresql log

**Comment by dvarrazzo** [comment] 2021-06-28 11:06
Are you using `with connection`?

**Comment by bimcas** [comment] 2021-06-28 11:20
I found some info in patroni issues [https://github.com/zalando/patroni/issues/1969](1969). Yesterday the new version of psycopg2 was released, it seems that autocommit = True is ignored in the with connection block: psycopg/psycopg2@e5ad0ab

So, I should still use psycopg2==2.8.6 for now.

**Comment by dvarrazzo** [comment] 2021-06-28 11:53
Duplicate of #1305.

**Closed by dvarrazzo** 2021-06-28 11:53 UTC
