### ISSUE TITLE
Provide Wheel (binary) distribution for OSX

### ISSUE THREAD

**Issue by adamhadani** [psycopg/psycopg2#479] opened 2016-10-04 22:24 UTC
Is this fairly easy to do / on the roadmap? 
We use OSX development machines and occasionally run into nasty errors when trying to compile psycopg2 from source, which in turn pulls some OpenSSL libraries which are not in standard location when using Homebrew with OSX. In general would be nice to be able to install psycopg2 quickly!

TL;DR what would be involved in getting a wheel for OSX? is it a CI build machine issue? Travis CI seems to support an OSX build environment, not sure what this project uses..

**Comment by aRkadeFR** [comment] 2016-10-05 06:59
Duplicate of https://github.com/psycopg/psycopg2/issues/425
and all others: https://github.com/psycopg/psycopg2/issues?utf8=%E2%9C%93&q=is%3Aissue%20wheel

**Comment by dvarrazzo** [comment] 2017-01-05 16:07
Psycopg moved on Travis, so it's a starting point I guess. We are also started building manylinux images, but locally, not on Travis. I'd be happy to have the images automatically built by Travis, but it seems somewhat tricky to download the images built.

@adamhadani If you, or someone else, provide adequate scripts to build and test osx wheel we will distribute them. I am no expert in OSX, I can't really figure out how people buildt `numpy-1.12.0rc2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl`... and I'm not sure I want to know.

**Comment by dvarrazzo** [comment] 2017-02-02 03:19
There is now a project to create wheels on Travis CI: https://github.com/psycopg/psycopg2-wheels

It will likely be extended with OSX build. When I have time. But @adamhadani if you can help with that it would be great. I want to release 2.7 soon and it would be great if the OSX wheels were ready for it.

**Comment by dvarrazzo** [comment] 2017-02-11 16:14
I have uploaded some test OSX wheels package on testpypi. Could you please check if they work?

    pip install -i https://testpypi.python.org/pypi psycopg2==2.7b1

Thank you very much.

**Comment by dvarrazzo** [comment] 2017-02-16 00:34
OSX packages are now created by Travis.

**Closed by dvarrazzo** 2017-02-16 00:34 UTC
Labels: osx
