### ISSUE TITLE
Psycopg chokes on utf-8 encoded server sent error messages.

### ISSUE THREAD

**Issue by cans** [psycopg/psycopg2#665] opened 2018-01-18 12:59 UTC
When one connects to Postgres server for which default locale of the machine on which it sits on, is not plain `'ascii'`, psycopg will not properly decode the message and raise a UnicodeDecodeError that will mask the actual error.

Way to reproduce:
- setup a system which default is in a locale UTF-8 (in my case a Debian with `fr_FR.UTF-8` as the default locale);
- setup a postgresql server on the system;
- create a role, a db accessible to that role and a table in that db, e.g. on with a `NON NULL` column;
- Send, through psycopg, a `INSERT` statement to fill up that table with data, some containing NULL in the non null column;
- Here comes your `IntergrityError` with it's translated message (again, in french here):
 `ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne \xc2\xab whatever \xc2\xbb\n`, which will be masked by a `UnicodeDecodeError`;

This issue seems to have existed for a [very long time](https://groups.google.com/forum/#!topic/sqlalchemy/bAqAVTe8IZM). It is not 100% clear to me who's responsibility it is to cope with that. But it seems reasonable that psycopg present higher level frameworks with data encoded as expected. Even for slightly "out-of-band" information. Yet again, not 100% sure where the responsibility of the issue lays.

I most recently experienced this with psycopg2 version 2.7.3.2 and Python 2.7.14.

**Comment by dvarrazzo** [comment] 2018-01-22 11:25
Of course the driver shouldn't choke on it.

In most code paths, receiving messages from the server, psycopg employs a forgiving approach: decode using the connection encoding but with "replace" error handling (but not for the data of course: bad data decoding will still give an error). So I would have said you should have received a message with some ? scattered in. Maybe somewhere we are not running through this code path.

There is also the added complication that the message is not correctly convertible in `ascii`. But on the other hand `ascii` doesn't really mean `ascii` for postgres, but it means something more akin `binary`.

I'll take a look.

**Comment by dvarrazzo** [comment] 2018-01-31 23:25
I don't seem to be able to reproduce the problem.

On an English (UK) computer I've created a French db cluster:

```
piro@makkuro:~/dev/psycopg2$ sudo locale-gen fr_FR.UTF-8
Generating locales (this might take a while)...
  fr_FR.UTF-8... done
Generation complete.

piro@makkuro:~/dev/psycopg2$ sudo pg_createcluster --locale fr_FR.UTF-8 9.6 testfr
Creating new PostgreSQL cluster 9.6/testfr ...
/usr/lib/postgresql/9.6/bin/initdb -D /var/lib/postgresql/9.6/testfr --auth-local peer --auth-host md5 --locale fr_FR.UTF-8
...
The database cluster will be initialized with locale "fr_FR.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "french".
...
```

The error is reported correctly:

```
piro@makkuro:~/dev/psycopg2$ PYTHONPATH=/home/piro/dev/psycopg2/build/lib.2.7 python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>> cnn = psycopg2.connect('port=5433 user=postgres')
>>> cur = cnn.cursor()
>>> cur.execute("create table test (data int not null)")
>>> cur.execute("insert into test values (null)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.IntegrityError: ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « data »
DETAIL:  La ligne en échec contient (null)
```

Note that although this is python 2 the guillemets are displayed ok. That is because the error is an utf8 encoded string and the connection is utf8. Trying to be frisky with the encoding doesn't cause much problems:

```
>>> cnn.set_client_encoding('latin1')
>>> cur.execute("select foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.ProgrammingError: ERREUR:  la colonne � foo � n'existe pas
LINE 1: select foo
               ^
```

the `replace` strategy avoids a decoding the error.

As far as I can see the error is not generated by psycopg but by something of yours handling the exception badly. I've tried setting LANG=POSIX to generate an exception on print but it didn't happen, and however if that was the case it wouldn't be psycopg fault anyway. That is, in my opinion psycopg is reporting the error right (the error is passed as utf8 and psycopg on Python 2 doesn't change encoding):

```
>>> try: cur.execute("select foo")
... except Exception as e: pass
... 
>>> e
ProgrammingError("ERREUR:  la colonne \xc2\xab foo \xc2\xbb n'existe pas\nLINE 1: select foo\n               ^\n",)
```

My usage of the error is to print it: my console is not broken by the utf8 and the exception is printed ok. If there was an error here it would be outside psycopg realm anyway.

```
>>> print e
ERREUR:  la colonne « foo » n'existe pas
LINE 1: select foo
               ^
```

I mean, of course there are a lot of ways to raise an exception when a string contains unicode:

```
>>> print unicode(e)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 20: ordinal not in range(128)
```

but that's not the driver fault.

As such, I'm closing this issue. If you are convinced that the error is within the driver (e.g. even `try: cur.execute(); except Exception as e` returns an encode/decode error instead of a database error into `e`) please provide a complete way to reproduce the error (a reproducible recipe or a Dockerfile).

**Closed by dvarrazzo** 2018-01-31 23:25 UTC
