### ISSUE TITLE
core dump on python:3.5.3-alpine with psycopg2

### ISSUE THREAD

**Issue by austinnichols101** [psycopg/psycopg2#511] opened 2017-02-20 21:35 UTC
I have a specific GraphQL query that triggers a `Segmentation fault (core dumped)` when running on the  `python:3.5.3-alpine` Docker image.  If I attempt the same query using an (otherwise identical, minimal difference) image based on the `python:3.5.3`  docker (non-alpine), the behavior does not occur.

I have a core dump, but there's not much info inside.  I'm looking for assistance in next steps to capture the data necessary to investigate further.

The evidence points to a potential problem with the psycopg2 library on alpine. (could this be related to musl being the compiler on alpine)?

**Comment by dvarrazzo** [comment] 2017-02-20 23:51
Hello, thank you for the report.

Different compiler or libc could be possibilities. Funnily enough I considered using alpine to create smaller test images for (this branch)[https://github.com/psycopg/psycopg2/commits/test_i686]. I didn't do it because I figured out results might have been not reliable.

If you [run the entire psycopg test suite](http://initd.org/psycopg/docs/install.html#running-the-test-suite) can you reproduce the segfault? If not, can you provide a test case I can reproduce in Docker?

I'll take a look if I can find a segfault using a modified version of [these images](https://github.com/dvarrazzo/manypython) based on alpine.

Thank you very much.

**Comment by dvarrazzo** [comment] 2017-02-21 00:33
I couldn't reproduce the problem. I ran a docker container with:

    docker run --rm -ti -v `pwd`:/psycopg2/ python:3.5.3-alpine /bin/sh

and followed roughly these steps:

```
# Build psycopg
cd /psycopg2
apk update
apk add postgresql-dev
apk add gcc
apk add musl-dev
python setup.py build

# Create a test database
apk add postgresql
su - postgres
initdb data
pg_ctl -D data/ -l /dev/null start
exit

# run the test suite
export PSYCOPG2_TESTDB_USER=postgres
export PSYCOPG2_TESTDB=postgres
export PYTHONPATH=`pwd`/build/lib.linux-x86_64-3.5/
python -c "from psycopg2 import tests; tests.unittest.main(defaultTest='tests.test_suite')" --verbose
```

The tests passed ok, no segfault.

Let me know if you can reproduce the issue, thank you.

**Comment by dvarrazzo** [comment] 2017-02-21 00:36
My tests were at commit 75747606, which should mean equivalent to 2.7 beta 2.

**Comment by dvarrazzo** [comment] 2017-03-16 18:43
Closing the issue as couldn't reproduce the bug in a clean environment. If you find a way to reproduce it let me know.

**Closed by dvarrazzo** 2017-03-16 18:43 UTC
