### ISSUE TITLE
Getting Illegal instruction error on macOS

### ISSUE THREAD

**Issue by samie820** [psycopg/psycopg2#696] opened 2018-03-26 08:43 UTC
After installation and connection to my django settings file I keep getting an 'illegal instruction: 4' error when i run any django command e.g python manage.py runserver

**Comment by dvarrazzo** [comment] 2018-03-26 09:46
Dupe of #685

Please install psycopg from source.

**Closed by dvarrazzo** 2018-03-26 09:46 UTC

**Comment by samie820** [comment] 2018-03-27 10:26
Thanks
