### ISSUE TITLE
 pycopg2 import issue on solaris 10

### ISSUE THREAD

**Issue by justin-wf** [psycopg/psycopg2#532] opened 2017-03-17 16:10 UTC
I have installed pycopg2 through pip3, not during import, I got an error. what is the issue?

```
# /opt/csw/bin/pip3 install psycopg2  

Collecting psycopg2
  Downloading psycopg2-2.7.1.tar.gz (421kB)
    100% |################################| 430kB 1.2MB/s 
Installing collected packages: psycopg2
  Running setup.py install for psycopg2 ... done
Successfully installed psycopg2-2.7.1
# python3
Python 3.3.6 (default, Mar 18 2016, 14:34:49) 
[GCC 5.2.0] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/csw/lib/python3.3/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: ld.so.1: python3.3: fatal: relocation error: file /opt/csw/lib/python3.3/site-packages/psycopg2/_psycopg.so: symbol timeradd: referenced symbol not found
```

**Comment by dvarrazzo** [comment] 2017-03-17 16:50
I guess:
```
symbol timeradd: referenced symbol not found
```

which some rapid googling finds you solaris is missing that function.

That function is missing from windows too: it is redefined in [win32_support.c](https://github.com/psycopg/psycopg2/blob/master/psycopg/win32_support.c)

So I guess what you can do is provide a patch with the proper ifdefs or adding a `solaris_support.c`, because I have no access to solaris. If you do it will be merged and released in psycopg 2.7.2. Thank you.

**Comment by qwexvf** [comment] 2017-04-04 12:44
Same issue after updating to latest version.

**Comment by dvarrazzo** [comment] 2017-04-04 13:23
@qwexvf yes, the issue is still open because it has not been fixed by any Solaris user. And it won't be fixed until a Solaris user will provide a patch. If you do in time, it will land in psycopg 2.7.2. If you don't, and nobody does, it will stay open for the foreseeable future. So it goes, as none of us has a Solaris machine to test, nor to my knowledge there is any open CI platform providing any (as there are for Linux, OSX, Windows).

If you can't provide a patch, please use `pip install "psycopg2<2.7"`.

**Comment by qwexvf** [comment] 2017-04-04 13:28
hmm. the fact is i'm not even a Solaris user.
Debian Jessie 64bits.

Btw, ``` psycopg2._psycopg ``` this _psycopg is a file ? i can see _psycopg.cpython-36m-x86_64-linux-gnu.so so i renamed it to _psycopg.so but yeah was not good idea.

Any suggestions ?

**Comment by dvarrazzo** [comment] 2017-04-04 13:40
I suggest to not add your comment under a bug called "pycopg2 import issue on solaris 10" if it's about debian. Also suggest not renaming files randomly you don't know what are for.

You can, for instance, open a new bug, describing what you do, what you expect to happen, what happens instead.

**Comment by qwexvf** [comment] 2017-04-04 13:45
ill do that then sorry bout that!

**Comment by mykarlsson** [comment] 2017-10-26 18:59
Hi. I'm able to reproduce this issue on Solaris 10 and have a made a PR that attempts to address it here: https://github.com/psycopg/psycopg2/pull/606

**Closed** 2017-11-28 03:26 UTC

**Comment by manmeetsaini** [comment] 2018-09-13 18:51
I'm experiencing a similar issue with missing symbol for PQlibVersion with Solaris 10 and psycopg2 2.7.5. Do we have any solution for this?

>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home/prodadm/python3/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: ld.so.1: python3.6: fatal: relocation error: file /export/home/prodadm/python3/lib/python3.6/site-packages/psycopg2/_psycopg.so: symbol PQlibVersion: referenced symbol not found

**Comment by manmeetsaini** [comment] 2018-09-13 18:57
@dvarrazzo : I'm also experiencing a similar issue with missing symbol for PQlibVersion with Solaris 10 and psycopg2 2.7.5. I have also installed this module via pip. Do you have any recommendation on how to resolve this? 

import psycopg2
Traceback (most recent call last):
File "", line 1, in 
File "/export/home/python3/lib/python3.6/site-packages/psycopg2/init.py", line 50, in 
from psycopg2._psycopg import ( # noqa
ImportError: ld.so.1: python3.6: fatal: relocation error: file /export/home/python3/lib/python3.6/site-packages/psycopg2/_psycopg.so: symbol PQlibVersion: referenced symbol not found

**Comment by dvarrazzo** [comment] 2018-09-15 23:32
@manmeetsaini smells like you are building with a version of libpq and linking dynamically with a different one but I can't be sure
