### ISSUE TITLE
The version 2.7.5 does not build on FreeBSD 11.2 amd64

### ISSUE THREAD

**Issue by WeZZard** [psycopg/psycopg2#774] opened 2018-09-21 19:24 UTC
When build the version 2.7.5 on FreeBSD 11.2 amd64, a macro actives the `round` function declaration at line 164 in `psycopg/config.h` and causes a conflict against the `round` function declaration at line 312 in `/usr/include/math.h`. FreeBSD community has already fixed this issue[1] on its own package distribution network with a little patch, and I request the community to fix this issue on the official repository.

[1] [Bug 230064 - databases/py-psycopg2: does not build with python 3.7](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230064)

**Comment by dvarrazzo** [comment] 2018-09-22 14:54
Dupe of #755

**Closed by dvarrazzo** 2018-09-22 14:54 UTC
