### ISSUE TITLE
OperationalError replaced by DatabaseError in 2.7 for disconnections

### ISSUE THREAD

**Issue by fizyk** [psycopg/psycopg2#527] opened 2017-03-14 11:33 UTC
I've updated psycopg2 in my project, and we're using https://github.com/ClearcodeHQ/pytest-postgresql for running postgresql and creating connections in tests, with sqlalchemy within project's code.

This pytest plugin disconnects all connections to the database at the end of a test before dumping all database's content. However when moving to psycopg2 2.7, we've started getting DatabseError instead of OperationalError for this.

**Comment by dvarrazzo** [comment] 2017-03-14 12:11
Can't reproduce. Both on unix and http socket I get OperationalError

```
In [4]: cnn = psycopg2.connect(port=54394)

In [5]: cur = cnn.cursor()

# meanwhile
# $ sudo pg_ctlcluster 9.4 main stop

In [6]: cur.execute("select 1")
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-6-ed09b4991cfa> in <module>()
----> 1 cur.execute("select 1")

OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

In [7]: psycopg2.__version__
Out[7]: '2.7.1.dev0 (dt dec pq3 ext lo64)'
```

can you post a script to reproduce it?

What you describe is not an expected change: with an accurate test we may find where exactly it occurs.

Also, I think this is bug #443 reoccurring. I'm afraid we merged that in 2.6.2 but we failed to merge it into master too. I'll sort out this mess but in the meantime more info would be useful. Can you test what is the behaviour with 2.6.1? If it works like 2.7 we have found the culprit I guess.

**Comment by dvarrazzo** [comment] 2017-03-14 14:44
Merged to master. Assuming it fixed your problem, so closing the ticket. Test is welcome: let us know if this was not the case.

**Closed by dvarrazzo** 2017-03-14 14:44 UTC

**Comment by dvarrazzo** [comment] 2017-03-14 15:10
Perfect, thank you for let us know. Too bad we released just yesterday :\
