### ISSUE TITLE
Python 3.13 on Windows11 - "pip install psycopg2-binary" is erroring, asking me to install the C++ 14.0 compiler

### ISSUE THREAD

**Issue by ChristopherMaurer** [psycopg/psycopg2#1732] opened 2024-10-08 02:15 UTC
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Before opening this ticket, please confirm that:**
- [x] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [x] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS: Windows 11
- Psycopg version: I don't know - it does not install
- Python version: 3.13
- PostgreSQL version:  16

**Problem Description**
installing psycopg2-binary is supposed to not require a C++ compiler, but it tries to build it anyway.  Then asks me to install 1.6GB of Microsoft C++ compiler.

=================   Output Display From pip install psycopg2========================
python -m pip install psycopg2-binary
Collecting psycopg2-binary
  Using cached psycopg2-binary-2.9.9.tar.gz (384 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: psycopg2-binary
  Building wheel for psycopg2-binary (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for psycopg2-binary (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\psycopg2
      copying lib\errorcodes.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\errors.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\extensions.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\extras.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\pool.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\sql.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\tz.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\_ipaddress.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\_json.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\_range.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\__init__.py -> build\lib.win-amd64-cpython-313\psycopg2
      running build_ext
      building 'psycopg2._psycopg' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psycopg2-binary
Failed to build psycopg2-binary
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (psycopg2-binary)

**Comment by ChristopherMaurer** [comment] 2024-10-08 02:23
Error msg includes "_Using cached psycopg2-binary-2.9.9.tar.gz (384 kB)_".  I guess that means it was trying to install 2.9.9 version.

**Comment by frenzymadness** [comment] 2024-10-08 06:32
The reason is that psycopg2-binary does not yet provide pre-compiled wheels for Python 3.13. See the available wheels here: https://pypi.org/project/psycopg2-binary/#files

**Comment by dvarrazzo** [comment] 2024-10-08 09:19
Duplicate of #1692, to be fixed by #1729.

**Closed by dvarrazzo** 2024-10-08 09:19 UTC

**Comment by AgungPN** [comment] 2024-10-15 03:03
is that issue release already? Cause I still have problem while try python:3.13 by docker with psycopg2. 

When I check in pypi latest release still "_Released: Oct 3, 2023_"

**Comment by fx-biocoder** [comment] 2026-06-01 14:36
This is an ongoing issue. It happens on Debian as well.

**Comment by dvarrazzo** [comment] 2026-06-01 15:17
I hardly believe that on Debian you are requested to install VS Code.

All the packages for Python 3.13 have been long solved. The rest is noise.
