### ISSUE TITLE
Datetime casting when DST changes and TIME ZONE/tzinfo_factory is set

### ISSUE THREAD

**Issue by g-as** [psycopg/psycopg2#1394] opened 2021-12-01 12:36 UTC
- OS: Debian bullseye
- Psycopg version: 2.9.2
- Python version: 3.9.9
- PostgreSQL version: 13
- pip version: 21.3.1

There seems to be an issue when both setting a time zone in PG and setting the same `ZoneInfo` time zone with `tzinfo_factory` for dates at DST cusp.

```python
with conn.cursor() as cur:
    cur.execute("SET TIME ZONE 'Europe/Paris'")
    cur.execute("SELECT '2013-10-27 00:00:00+0'::timestamptz")
    a = cur.fetchone()[0]
    cur.execute("SELECT '2013-10-27 01:00:00+0'::timestamptz")
    b = cur.fetchone()[0]

>>> a
datetime.datetime(2013, 10, 27, 2, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200)))

>>> b
datetime.datetime(2013, 10, 27, 2, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600)))
```
The result here here is correct since on this date `Europe/Paris` switched from UTC+2 to UTC+1.

If we add the `tzinfo_factory`:
```python
def tzinfo_factory(offset):
    return zoneinfo.ZoneInfo("Europe/Paris")

with conn.cursor() as cur:
    cur.tzinfo_factory = tzinfo_factory
    cur.execute("SET TIME ZONE 'Europe/Paris'")
    cur.execute("SELECT '2013-10-27 00:00:00+0'::timestamptz")
    a = cur.fetchone()[0]
    cur.execute("SELECT '2013-10-27 01:00:00+0'::timestamptz")
    b = cur.fetchone()[0]

>>> a
datetime.datetime(2013, 10, 27, 2, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Paris'))

>>> b
datetime.datetime(2013, 10, 27, 2, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Paris'))

>>> a == b
True
```

Here I would expect `b` to be equal to:
```python
>>> datetime.datetime(2013, 10, 27, 1, tzinfo=datetime.timezone.utc).astimezone(zoneinfo.ZoneInfo("Europe/Paris"))
datetime.datetime(2013, 10, 27, 2, 0, fold=1, tzinfo=zoneinfo.ZoneInfo(key='Europe/Paris'))
```

I haven't used the `offset` arg in `tzinfo_factory`, so I guess some information is lost there. But that's the way django implements it.

Let me know if you need some extra info.

Cheers

**Comment by g-as** [comment] 2021-12-03 14:19
FYI, `psycopg3` works as expected:
```python
with psycopg.connect(os.environ["DATABASE_URL"]) as conn:
    with conn.cursor() as cur:
        cur.execute("SET TIME ZONE 'Europe/Paris'")
        cur.execute("SELECT '2013-10-27 00:00:00+0'::timestamptz")
        a = cur.fetchone()[0]
        cur.execute("SELECT '2013-10-27 01:00:00+0'::timestamptz")
        b = cur.fetchone()[0]

>>> a
datetime.datetime(2013, 10, 27, 2, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Paris'))

>>> b
datetime.datetime(2013, 10, 27, 2, 0, fold=1, tzinfo=zoneinfo.ZoneInfo(key='Europe/Paris'))
```

**Comment by dvarrazzo** [comment] 2021-12-06 12:00
Hello,

I see the error happening in this case, yes, but Django is using tzinfo_factory the wrong way. It should return be a type, or something with the same interface, instead Django is using it to return a specific value.

We parse the string representation of the Postgres timezones, so we see, in your cases:
```
2013-10-27 02:00:00+02
2013-10-27 02:00:00+01
```
what we do is to parse the offset and ask `tzinfo_factory` to return an object representing _that offset_. Your sample implementation:
```python
def tzinfo_factory(offset):
    return zoneinfo.ZoneInfo("Europe/Paris")
```
discards that information.

What I think, remembering old versions of Django, is that they pictured people storing timestamp without time zone in the database (because maybe that's what sqlite does) and then would have wanted to display them in a configured timezone (being surprised if that wasn't Chicago). In that case there is no chance of detecting if a naive timestamp is this way or the other of the DST time machine. However, when the database happens to know it and returns a tz-aware timestamp, things get funnier.

I think Django can be fixed by stopping the customisation of the cursor tzinfo_factory and using instead a customized loader for timestamp and timestamptz, the latter to invoke `astimezone()` on the timestamp returned by the basic implementation (the former might just use `replace()`. Psycopg is doing the right thing, within the kind of stuff that tzinfo_factory was designed to do.

Is this analysis fair, @fogzot?

Psycopg 3 works in different way, for several reasons: because there are now standard implementations of datetime and of timezone in the stdlib and because it has to deal uniformly with text and binary values from the database, and the binary values are always returned as UTC, regardless of the connection timezone settings.

**Closed by dvarrazzo** 2021-12-06 12:00 UTC

**Comment by g-as** [comment] 2021-12-06 12:17
A'ight. Thank you very much for the detailed feedback. I'll report the issue at django.
