### ISSUE TITLE
pg_config is deprecated in some distros

### ISSUE THREAD

**Issue by sadko4u** [psycopg/psycopg2#1203] opened 2020-12-01 12:51 UTC
For some Linux Distributions, **pg_config** tool is deprecated.
Maintainers recommend to use standard **pkg-config** tool instead.
Would be nice if you could add the corresponding workaround.

https://lists.opensuse.org/opensuse-factory/2019-03/msg00299.html

**Comment by dvarrazzo** [comment] 2020-12-01 12:56
I don't use suse. If you do documentation patch is welcome.

**Comment by sadko4u** [comment] 2020-12-02 08:51
I don't use Debian-based distros nor FreeBSD. But when necessary, I install a virtual machine:

https://github.com/sadko4u/lsp-plugins/issues/154

Moreover, I'm not a python developer do deeply dig into code and build process of the library.

**Comment by dvarrazzo** [comment] 2021-06-16 12:17
Duplicate of #1001

**Closed by dvarrazzo** 2021-06-16 12:17 UTC
