### ISSUE TITLE
itersize vs page_size

### ISSUE THREAD

**Issue by sam-s** [psycopg/psycopg2#797] opened 2018-10-26 13:40 UTC
`itersize` in [cursor](http://initd.org/psycopg/docs/cursor.html) defaults to 2000.
`page_size` in [execute_values](http://initd.org/psycopg/docs/extras.html#psycopg2.extras.execute_values) defaults to 100.

1. Why are they named inconsistently? (shouldn't `page_size` be `pagesize`?)
1. Why are their defaults so different?
1. What happens if I pass `None` explicitly as in `execute_values(... page_size=None)` or set `cursor.itersize=None`?

Thank you very much!

**Comment by dvarrazzo** [comment] 2018-10-26 14:57
They are pretty much arbitrary. `itersize` (maybe should have been called `iter_size`) is in output, and was chosen to fetch enough data to have not gigantic pages if records are reasonably small. With 500B records, 2000 records are 1MB. For me it could have been much smaller: 100 would have reduced by a factor 100 the number of roundtrips, which sounds reasonable as well. That's the rationale I picked for `execute_values`' `page_size`.

1) As a preference (in the past we bikeshedded between `readonly` vs. `read_only` in ML) I've seen a precedence for the `snake_case` rather than `crammedcase`: `itersize` might have slipped the care (we are talking about 2011, I think our level of attention has raised since). I don't know if just a matter of habit, but `iter_size` makes my brain miss a beat, it doesn't flow...

2) They are two unrelated things. I don't remember a report of 2000 being too big, but it feels a bit big for me. I wouldn't change that value (or that name, for the matter) in psycopg2. Maybe in psycopg3...

3) I guess it is implementation dependant, and you can expect a `TypeError`.

This is not a bug anyway, so closing here.

**Closed by dvarrazzo** 2018-10-26 14:57 UTC

**Comment by sam-s** [comment] 2018-10-26 16:14
Thank you very much for your reply!

> I guess it is implementation dependant, and you can expect a TypeError.

I am confused - the question was about the very specific implementation - _yours_ (`psycopg2`).

**Comment by fogzot** [comment] 2018-10-26 16:43
About `snake_case` vs `crammedcase`, it is a DB-API thing: check https://www.python.org/dev/peps/pep-0249/ and you'll see that all properties are `crammedcase`.
