### ISSUE TITLE
testNetworkArray: AssertionError: Lists differ: [Inet('192.168.0.1/24')] != ['192.168.0.1/24']

### ISSUE THREAD

**Issue by df7cb** [psycopg/psycopg2#948] opened 2019-07-31 15:49 UTC
I'm working on updating the Debian package of psycopg2 to 2.8.x. Previously, we didn't have any testsuites activated, and I'm trying to change that.

Now, in some build environments, there's a test failure that I can't explain:

```
16:38:04 test_set_encoding (tests.test_quote.TestStringAdapter) ... ok
16:38:04 
16:38:04 ======================================================================
16:38:04 FAIL: testNetworkArray (tests.test_types_basic.TypesBasicTests)
16:38:04 ----------------------------------------------------------------------
16:38:04 Traceback (most recent call last):
16:38:04   File "tests/testutils.py", line 286, in skip_before_postgres__
16:38:04     return f(self)
16:38:04   File "tests/test_types_basic.py", line 406, in testNetworkArray
16:38:04     self.assertEqual(a, ['192.168.0.1/24'])
16:38:04 AssertionError: Lists differ: [Inet('192.168.0.1/24')] != ['192.168.0.1/24']
16:38:04 
16:38:04 First differing element 0:
16:38:04 Inet('192.168.0.1/24')
16:38:04 '192.168.0.1/24'
16:38:04 
16:38:04 - [Inet('192.168.0.1/24')]
16:38:04 ?  -----                -
16:38:04 
16:38:04 + ['192.168.0.1/24']
16:38:04 
16:38:04 ----------------------------------------------------------------------
16:38:04 Ran 770 tests in 6.079s
16:38:04 
16:38:04 FAILED (failures=1, skipped=144)
16:38:04 E: pybuild pybuild:341: test: plugin distutils failed with: exit code=1: cd /tmp/autopkgtest.3whzdc/tree/.pybuild/cpython2_2.7/build; python2.7 -m unittest discover -v 
```
This is with Debian unstable, PostgreSQL 9.4.23-1.pgdg+1, python 2.7.16-3, psycopg2 2.8.3, but I don't think the PG version is relevant.
The failure doesn't happen in all environments. In one case, the build fails rightaway (https://salsa.debian.org/python-team/modules/psycopg2/-/jobs/247067), in a different environment, building works, but then an additional step that runs the tests on the installed packages fails (https://pgdgbuild.dus.dg-i.net/job/psycopg2-binaries/2/architecture=amd64,distribution=sid/consoleFull). On my notebook, the tests works with all PG and all python versions, so I can't really debug it.

It's only that test that has the problem, the test on the next line (`{192.168.0.0/24}'::cidr[]` instead of `::inet[]`) works.

Any idea?

**Comment by dvarrazzo** [comment] 2019-07-31 16:37
Are you sure you are running a test suite consistent with the psycopg code?

Your code seems running:

    python2.7 -m unittest discover -v

which might be right or wrong, but it's not the way we run our test suite, which looks like:

    python -c import tests; tests.unittest.main(defaultTest='tests.test_suite')

(see `Makefile` and `scripts/travis_test.sh`)

I wonder if that changes something.

**Comment by df7cb** [comment] 2019-07-31 16:46
`-m unittest discover` is what I got from Debian's "pybuild" scripts. I'll give the other way a try as well, but I guess it won't matter since the tests are running successfully in some cases.
(Will take until next week however, I'm actually on vacation and started looking only becase pgadmin4 got broken with their latest version. Thanks for the prompt reply!)

**Comment by dvarrazzo** [comment] 2019-09-04 11:33
Any followup on this? I'm inclined to close the issue.

**Comment by df7cb** [comment] 2019-09-04 12:26
Sorry I got distracted by other things. I'm running the testsuites again now and will report back.

**Comment by df7cb** [comment] 2019-09-04 13:10
I can still see that same error when using your suggested test command: https://salsa.debian.org/python-team/modules/psycopg2/-/jobs/305991

**Comment by dvarrazzo** [comment] 2019-09-04 13:56
In the link you post I don't see my command: I see

```
I: pybuild base:217: cd /builds/python-team/modules/psycopg2/debian/output/psycopg2-2.8.3/.pybuild/cpython2_2.7_psycopg2/build; python2.7 -m unittest discover -v 
```

My command is:

```
python -c import tests; tests.unittest.main(defaultTest='tests.test_suite')
```

Trying your command, yes, I can confirm the failure. But it's a false positive: it's probably caused by tests running in a different order. I'll push a thing to make them more reproducible.

**Comment by df7cb** [comment] 2019-09-05 13:27
Thanks!

**Closed** 2019-09-05 13:53 UTC
