### ISSUE TITLE
[With SQLAlchemy] Impossible to insert subarray of nulls in multidimensional arrays

### ISSUE THREAD

**Issue by eoghanmurray** [psycopg/psycopg2#706] opened 2018-04-26 22:19 UTC
This is a transfer of [a bug I reported in SqlAlchemy](https://bitbucket.org/zzzeek/sqlalchemy/issues/4244/impossible-to-insert-subarray-of-nulls-in), as I believe the problem isn't in that library (but I may be wrong).

Test case with sqlalchemy:
```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.dialects.postgresql import ARRAY

Base = declarative_base()


class Test (Base):

    __tablename__ = 'test_subarray_nulls'

    id = Column(Integer, primary_key=True)
    pay = Column(ARRAY(Integer))

e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
Base.metadata.create_all(e)

s = Session(e)
member = Test()
member.pay = [None]  # A: fine
member.pay = [[1, 1]]  # B: fine
member.pay = [[None, 2]]  # C: fine
member.pay = [[3, None]] # D: fine
member.pay = [[4, 4], [None, None]] # E: fine
member.pay = [[None, None]] # F: error
s.add(member)
s.commit()
```

Output:
```
[snip]
2018-04-26 14:08:34,264 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2018-04-26 14:08:34,265 INFO sqlalchemy.engine.base.Engine INSERT INTO test_psycopg_4 (pay) VALUES (%(pay)s) RETURNING test_psycopg_4.id
2018-04-26 14:08:34,265 INFO sqlalchemy.engine.base.Engine {'pay': [[None, None]]}
2018-04-26 14:08:34,266 INFO sqlalchemy.engine.base.Engine ROLLBACK
[snip (traceback)]
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "pay" is of type integer[] but expression is of type text[]
LINE 1: INSERT INTO test_subarray_nulls (pay) VALUES (ARRAY['{NULL, NULL}...
                                                 ^
HINT:  You will need to rewrite or cast the expression.
```

If I understand it correctly, it's converting `member.pay = [None]` to `INSERT INTO test_subarray_nulls (pay) VALUES ('{null}');` (haven't been able to check if this is actually what happens).
but `member.pay = [[None, None]]` is getting converted to `VALUES (ARRAY['{NULL, NULL}'])` causing the error.
`VALUES ('{{NULL,NULL}}')` would work in postgresql

**Comment by zzzeek** [comment] 2018-04-26 23:44
as I mentioned on the SQLAlchemy issue psycopg2 might not have enough information to work from here since it needs to know about "integer".  So if there were a type handler that could be passed some kind of null_int object, or something, so psycopg2 knows how to format this.

**Comment by dvarrazzo** [comment] 2018-04-27 11:14
Psycopg can be told so by generating a query such as `insert ... values (%s::int[])`. 

Alternatively maybe we could think about changing the int array typecaster. But it seems to me here that SA has enough info to generate the "casting placeholder"?

**Comment by dvarrazzo** [comment] 2018-04-27 13:58
@zzzeek I'm not sure I understand what you mean, sorry. What do you mean "scanning the string for the cast"?

**Comment by zzzeek** [comment] 2018-04-27 14:49
@dvarrazzo per the error message, psycopg2 is rendering like this:

VALUES (ARRAY['{NULL, NULL}'])

if I add ::int[] to that, still does not work:

# select ARRAY['{NULL, NULL}']::int[];
ERROR:  invalid input syntax for integer: "{NULL, NULL}"

If I send the query as "VALUES(%s::int)"  vs. "VALUES(%s)",  how does the final string passed to the database differ?

**Comment by dvarrazzo** [comment] 2018-04-27 15:12
Ok yes, I understand: sorry, I misread the problem. This is actually a duplicate of bug #325.

The last changes to the bit in question are in commit b0058c0cc85a0e9ce88ccacef0bc34a26d8e5d89. While a generic solution would be to only use the `{}` syntax, I think we can special-case the array and make it use `{}` if all the components are either `None` or lists of `None`. It seems that these work:

```
=# select ARRAY[ARRAY[1, NULL], '{NULL, NULL}']::int[][];
         array          
------------------------
 {{1,NULL},{NULL,NULL}}

=# select ARRAY['{NULL, NULL}', ARRAY[1, NULL]]::int[][];
         array          
------------------------
 {{NULL,NULL},{1,NULL}}
```

This doesn't instead:

```
=# select ARRAY['{NULL, NULL}', '{NULL, NULL}']::int[][];
ERROR:  invalid input syntax for integer: "{NULL, NULL}"
```

Maybe this can be fixed ok in the next bugfix and for the above case generate `{{NULL,NULL},{NULL,NULL}}`.

I'll try to work on that the next week. However patches are welcome.

**Comment by zzzeek** [comment] 2018-04-27 15:32
I'm happy that this is considered to be doable on the psycopg2 side!

**Closed** 2018-05-20 11:52 UTC
