### ISSUE TITLE
ERROR: Failed building wheel for psycopg2

### ISSUE THREAD

**Issue by AlphaMAtrix69** [psycopg/psycopg2#1701] opened 2024-05-27 04:34 UTC
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Before opening this ticket, please confirm that:**
- ☑️ I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- ☑️ I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- ☑️ If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS: Windows 11 Pro
- Psycopg version: 2.9.9
- Python version:  3.13.0a3
- PostgreSQL version: psql (PostgreSQL) 16.3
- pip version: 24.0

Here is the error I am getting while installing psycopg2 with the `pip install psycopg2` cmd

Creating library build\temp.win-amd64-cpython-313\Release\psycopg\_psycopg.cp313-win_amd64.lib and object build\temp.win-amd64-cpython-313\Release\psycopg\_psycopg.cp313-win_amd64.exp
      utils.obj : error LNK2001: unresolved external symbol _PyInterpreterState_Get
      build\lib.win-amd64-cpython-313\psycopg2\_psycopg.cp313-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
Failed to build psycopg2
ERROR: Could not build wheels for psycopg2, which is required to install pyproject.toml-based projects

**Comment by dvarrazzo** [comment] 2024-05-27 11:40
Python 3.13 is not supported yet.

Duplicate of #1692.

**Closed by dvarrazzo** 2024-05-27 11:40 UTC

**Comment by tommed** [comment] 2024-12-13 11:19
Could you please mention the versions of Python (or latest version of Python) which supported by this library on your README please. It's taken me a while to find this ticket.
