### ISSUE TITLE
psycopg2.NotSupportedError: ROW expression, implicit or explicit, is not supported in target list

### ISSUE THREAD

**Issue by anthnyprschka** [psycopg/psycopg2#882] opened 2019-04-04 10:22 UTC
Hi, i am trying something like the following:

```
query = """
	create temp table stage (like {table}); 
	insert into stage ({columns})
	values ({values});

	begin transaction;
	delete from {table} 
	using stage 
	where {table}.document_id = stage.document_id 
	and {table}.field = stage.field
	and {table}.created_at = stage.created_at;
	insert into {table} 
	select * from stage;
	end transaction;

	drop table stage;

	commit;
	""".format(
		table=redshift_table,
		columns=columns,
		values=values
	)

cur = con.cursor()
cur.execute(query) 
con.close() 
```

However, when i try to run it, it will throw me the following error:
`psycopg2.NotSupportedError: ROW expression, implicit or explicit, is not supported in target list`. I couldn't find any related information on google, and the psycopg2 repo.

**Comment by dvarrazzo** [comment] 2019-04-04 12:19
This is an error from the server. The query you are generating is wrong. Likely it's `column` but I'm not sure.

Look at your query as generated after the placeholders (e.g. `cur.query`), run it in psql, fix it, adjust it.

This is not a bug. Closing here. If you have more questions write the mailing list, not here.

**Closed by dvarrazzo** 2019-04-04 12:19 UTC

**Comment by anthnyprschka** [comment] 2019-04-04 13:20
Thanks @dvarrazzo !
